### ISSUE TITLE
Module index tables in doc comments aren't marked up

### ISSUE THREAD

**Issue by dsheets** [lpw25/opam-doc-base#12]
The `{!modules: ModA ModB ...}` construct is stored as a single text node containing the strings of the module names: `ModA ModB`. No indication of the index table construct or markup of module names is present.

**Comment by dsheets** [comment]
This shows up as `Ref (Link module_list_string, None)` which is weird.

**Comment by lpw25** [comment]
This is a bug in the compiler patch.

**Comment by lpw25** [comment]
Fixed in compiler
