### ISSUE TITLE
Doc comments with subscript constructs are empty

### ISSUE THREAD

**Issue by dsheets** [lpw25/opam-doc-base#14]
If a documentation comment includes the `{_ ...}` subscript text construct, the comment node is output but the content is empty.

**Comment by samoht** [comment]
This one seems to be a bug in the ocamldoc parser itself. In that case the `cmti` stores `Style(SK_custom "_xxx",[])` instead of `Style(SK_subscript,["xxx"])`. I'll push a workaround for now on.

**Comment by samoht** [comment]
Keeping it open as it seems to be a bug in the compiler parser patch.

**Comment by lpw25** [comment]
This is now fixed in the compiler. #44 removes the work-around.
