### ISSUE TITLE
References are not included in the XML (or parsed input)

### ISSUE THREAD

**Issue by dsheets** [lpw25/opam-doc-base#19]
Use of the `{! Ident}` construct will result in the plaintext of `Ident`. `Ident` is not marked up in any way.

**Comment by samoht** [comment]
Not sure how to repro this one. There's a support for module, module type, types and values (and I've added support for random links). There are still few which are missings, namely: "elements" -- not idea what it is --, classes and class types, exceptions, attributes, methods, sections, recfields -- not idea what it is -- and const -- no idea what is is--

**Comment by dsheets** [comment]
I don't understand what you mean... we need both kind-specific references like for the categories you mention as well as generic references. None of them show up as actual elements. They are just plain text (well, a few are now marked up with TODO constructors).

**Comment by dbuenzli** [comment]
@samoht the meaning of references qualifiers is documented [here](http://caml.inria.fr/pub/docs/manual-ocaml-4.02/ocamldoc.html#sec326).

**Comment by lpw25** [comment]
Issue moved to lpw25/doc-ock-lib#1.
