### ISSUE TITLE
Content of @ tags is dropped.

### ISSUE THREAD

**Issue by dsheets** [lpw25/opam-doc-base#22]
`@author`, `@deprecated`, `@param`, `@return`, `@raise`, `@see`, `@since`, `@before`, `@version`,  and custom tag bodies are all dropped.

**Comment by samoht** [comment]
done

**Comment by dsheets** [comment]
`@raise`, `@param`, `@before` have empty second textual arguments and all of their parameters shoved into their first string parameter.

**Comment by dsheets** [comment]
Custom tags show up not as documentation tags but custom styles in text elements with the argument to the `Custom` constructor as `?` and the tag name prepended to the markup body.

**Comment by samoht** [comment]
Should be better with 7a5e0dcd1181fb08ff32f5c9cc6541b2c7ed2c22 (which changes the XML schema to no be ambiguous)
