### ISSUE TITLE
Nested module signatures don't link to their content

### ISSUE THREAD

**Issue by dsheets** [lpw25/opam-doc-base#26]

**Comment by lpw25** [comment]
Nested module signatures are supposed to be empty. Their contents is available in a separate file.

**Comment by dsheets** [comment]
I have changed the title to "Nested module signatures don't link to their content".

**Comment by dsheets** [comment]
Why are there multiple XML files for a single interface?

**Comment by dsheets** [comment]
When #49 is merged, this will be fixed.
