### ISSUE TITLE
Polymorphic variants are not supported

### ISSUE THREAD

**Issue by dsheets** [lpw25/opam-doc-base#27]

**Comment by samoht** [comment]
Are you using my branch?

**Comment by lpw25** [comment]
Note that displaying recursive polymorphic variants correctly is quite tricky,  so if you try to add support for them I would recommend failing gracefullying on recursion rather than trying to get the printing correct.

**Comment by dsheets** [comment]
Could you give an example of one of these recursive polymorphic variants with tricky printing?

**Comment by lpw25** [comment]
To be more precise, it is the printing of aliased polymorphic variants (and objects) that is a pain. So anything like `[>`Foo of int ] as 'a -> 'a`.

I think that `mark_types` could fail reasonably gracefully by just never marking a polymorphic variant type as aliased. So the above type would be printed `[> `Foo of int] -> [> `Foo of int]`.

**Comment by lpw25** [comment]
Fixed by #47
