### ISSUE TITLE
OpamDocTypes uses ambiguous field names

### ISSUE THREAD

**Issue by dsheets** [lpw25/opam-doc-base#3]
`path`, `modules`, `doc` are ambiguous and cause silly type errors that do not allude to the ambiguity. Will users have to annotate all of their `library` values so they are not assumed to be `package`s, `module`s, `module_type`s, or `api`s?

**Comment by lpw25** [comment]
I've been annotating my functions with types to disambiguate constructors. I think I prefer it to all the `PFoo`, `TFoo` etc. stuff in the OCaml compiler.

**Comment by dsheets** [comment]
It's the record field names that are annoying me. Usually, you don't have to provide annotations to get a compile to happen. Is there some warning that needs to be turned on to give you some hint that the type error you are seeing is a misinferred ambiguity?

What about using submodules for each of the types so that record fields can be duplicated by unambiguous in the module scope?

**Comment by lpw25** [comment]
The new doc-ock-lib interface keeps all these records in separate modules (by using many mutually recursive modules) which should avoid this issue.
