### ISSUE TITLE
What is a Block text element?

### ISSUE THREAD

**Issue by dsheets** [lpw25/opam-doc-base#32]
What do I write in my docs to generate a `Block` text element, @samoht, @lpw25?

**Comment by lpw25** [comment]
Ah, it seems that you can't. It is a member of the `text_element` type in original ocamldoc, but is not actually a text element. So we should remove it from our `text_element` type.

**Comment by samoht** [comment]
Fixed by 9d9b7b0cdc625c069d7c8c911df0936b80ecbcc7

**Comment by samoht** [comment]
Keeping it open as it needs an action on the compiler patch. I've just removed the construct in `opamDocType` and added an `assert false` whenever we found one `Block` in an attribute.

**Comment by lpw25** [comment]
This is now fixed in the compiler. #44 removes the handling of `Block`.
