### ISSUE TITLE
OpamDocXml says xml a lot in identifiers

### ISSUE THREAD

**Issue by dsheets** [lpw25/opam-doc-base#5]
``` ocaml
val module_to_xml: Xmlm.output -> OpamDocTypes.module_ -> unit

val module_of_xml: Xmlm.input -> OpamDocTypes.module_

val module_type_to_xml: Xmlm.output -> OpamDocTypes.module_type -> unit

val module_type_of_xml: Xmlm.input -> OpamDocTypes.module_type

val library_to_xml: Xmlm.output -> OpamDocTypes.library -> unit

val library_of_xml: Xmlm.input -> OpamDocTypes.library

val package_to_xml: Xmlm.output -> OpamDocTypes.package -> unit

val package_of_xml: Xmlm.input -> OpamDocTypes.package
```

I expected `of_module`, `to_module`, `of_module_type`, `to_module_type`, etc. I suppose it comes down to whether you expect your users to open your module or refer to it with a path. Personally, I prefer to do something like `module DocXml = OpamDocXml` and then `DocXml.to_module` or `DocXml.of_module`, etc.

**Comment by lpw25** [comment]
Yeah I should rename them. Originally they weren't in their own module, and I didn't rename them when they moved.

**Comment by lpw25** [comment]
This interface is now subsumed by doc-ock-xml (to be released over the weekend), so I'm closing this issue.
