### ISSUE TITLE
Mutually recursive types' recursion not maintained

### ISSUE THREAD

**Issue by dsheets** [lpw25/opam-doc-base#52]
I don't know if this is represented in cmti or if it has to be reconstructed.

``` ocaml
(** This comment is for {!mutual_constr_a} and {!mutual_constr_b}. *)
type mutual_constr_a =
| A
| B_ish of mutual_constr_b
and mutual_constr_b =
| B
| A_ish of mutual_constr_a
```

becomes

```
type mutual_constr_a =
| A
| B_ish of mutual_constr_b
This comment is for mutual_constr_a and mutual_constr_b.
type mutual_constr_b =
| B
| A_ish of mutual_constr_a
```

**Comment by lpw25** [comment]
I think that we should deliberately not retain recursion information. It is a scoping issue and we have already resolved all references so no longer care about scoping. It is also a real pain to maintain for recursive modules, and I'd rather not do it at all than only do it sometimes.
