### ISSUE TITLE
`module type of` references inlined

### ISSUE THREAD

**Issue by dsheets** [lpw25/opam-doc-base#56]
``` ocaml
(** module type of *)
module type COLLECTION = module type of CollectionModule
```

shows up in XML with the signature of `CollectionModule` inlined as the definition of `COLLECTION`.

**Comment by lpw25** [comment]
Note that this will always be the case with .cmi generation. However, .cmti generation should do better.

**Comment by lpw25** [comment]
Fixed for .cmti files in doc-ock-lib.
