### ISSUE TITLE
module signature constraints inlined

### ISSUE THREAD

**Issue by dsheets** [lpw25/opam-doc-base#57]
``` ocaml
module type MMM = sig module C : COLLECTION end

module type RECOLLECTION = MMM with module C = Recollection(CollectionModule)
```

shows up in XML with the signature of `Recollection(CollectionModule)`, with constraints applied, inline as the definition of `C` in `RECOLLECTION`.

**Comment by lpw25** [comment]
For .cmi files this is always going to be the case as `with` is no longer present at that stage. For .cmti files this is fixed in doc-ock-lib, although it will not be possible to get back the expanded version until lpw25/doc-ock-lib#2 is resolved.
