### ISSUE TITLE
Polymorphic variant constructors not in source order

### ISSUE THREAD

**Issue by dsheets** [lpw25/opam-doc-base#65]

**Comment by dsheets** [comment]
The ordering is not currently reversed. It's probably something like hash order? Is it possible to get the source order out of cmti?

**Comment by lpw25** [comment]
We can get the source order from .cmti but not .cmi.

The current order is not even the hash order used by OCaml for its error printing as the order seems to get messed up in the .cmi, so I've added a call to sort so that the order at least matches the order that OCaml prints.

**Comment by lpw25** [comment]
In doc-ock-lib they should now be in source order for .cmti files(reopen the issue if they don't). For .cmi files we produce the same order as OCaml's own type printer which is the best we can do.
