### ISSUE TITLE
Polymorphic variant unions inlined

### ISSUE THREAD

**Issue by dsheets** [lpw25/opam-doc-base#66]
``` ocaml
(** This comment is for [poly_variant_union]. *)
type poly_variant_union = [
| poly_variant
| `TagC
]
```

**Comment by dsheets** [comment]
ocamldoc also inlines this (but that seems wrong).

**Comment by lpw25** [comment]
This is due to OCaml not keeping track of unions (which I personally think is a mistake in OCaml), so .cmi file output will not be able to handle this case. When .cmti output handles types itself (rather than just deferring to the .cmi type printer) it will handle these cases properly.

**Comment by dsheets** [comment]
What is ".cmti handl[ing] types itself"? Is this a separate piece of work that is planned for the compiler? Is there a mantis issue?

**Comment by dbuenzli** [comment]
Yes inlining here is sometimes annoying with big unions where you just want to add one or two cases and it repeats everything. Not inlining is also helpful to remind you which name you can use to handle the other cases in bulk (that `#poly_variant` pattern notation).

**Comment by lpw25** [comment]
> What is ".cmti handl[ing] types itself"?

Most of the code for handling .cmti files in opam-doc-base just passes the type information to the code for handling .cmi files, which means it ignores any extra information present in the .cmi files. Fixing this is part of the "support all OCaml features work" (in fact I'm starting by getting all features working on .cmti's and then adding them all for .cmi's as well).

**Comment by lpw25** [comment]
This is handled correctly in doc-ock-lib (although not technically tested) for .cmti's. Support for .cmi's is not really possible without large changes to OCaml's type-checker, so I'm going to close this issue.
